import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="" style={{
          display:"flex",
          justifyContent:"center",
          alignItems:"center",
          width:"100vw",
          height:"100vh",
          gap:"10px",
          backgroundColor:"black",
          flexDirection:"column"
        }}>
        {children}
        </div>
      </body>
    </html>
  );
}
